# Task 1:

1. Write a function to compute 5/0 and use try/except to catch the exceptions.

In [17]:
def compute(val):
    try:
        x = val/0
        print(x)
    except:
        print("The value can not be devisible by 0(zero)")

compute(5)

The value can not be devisible by 0(zero)


2.  Implement a Python program to generate all sentences where subject is in ["Americans",
    "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
    Hint: Subject,Verb and Object should be declared in the program as shown below.
    
subjects=["Americans ","Indians"]

verbs=["play","watch"]

objects=["Baseball","Cricket"]

Output should come as below:
    
Americans play Baseball.

Americans play Cricket.

Americans watch Baseball.

Americans watch Cricket.

Indians play Baseball.

Indians play Cricket.

Indians watch Baseball.

Indians watch Cricket.

In [8]:
subjects=["Americans","Indians"]
verbs=['play','watch']
objects=['Baseball','Cricket']
a=[ (str(i)+" "+str(j)+" "+str(k))  for i in subjects for j in verbs for k in objects]
for i in a:
    print (i)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


# Task 2:

 1.  Write a function so that the columns of the output matrix are powers of the input vector.

    The order of the powers is determined by the increasing boolean argument. Specifically, when
    increasing is False, the i-th output column is the input vector raised element-wise to the power
    of N - i - 1.
    
    HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
    Theophile Vandermonde.

In [7]:
import numpy as np 
N = 6 # Taken input as 5
List_A_define = [1,2,3,4] # Define Dumpy List of Values
def Vander_JD(List_A,N):
    # Created Numpy with Zero Shape of Row (as List length ) and Columns (as N input)
    Np_Array = np.zeros(shape=(len(List_A_define), N),dtype=int)
    for j in enumerate(List_A): # Enumerating over list getting tuple
        Np_Array[j[0]][-1] = 1 # Fixing Last Position (RXC) as Fix with 1
        Np_Array[j[0]][-2] = j[1] # Fixing 2nd last Postion as Element in List
        if N <= 3: # Condtion with When N is less than or eqal to 3
            Np_Array[j[0]][0]  =int(j[1])*int(j[1]) # inserting result according to postion of
        else: 
            diff = N-3 
            for k in (range(N-2)): 
                counter = 1 
                for t in enumerate(List_A): # Enumeration for positon and element
                    delta = int(k)+1 # Dummy variable set to Zero in Multiply
                    Cal_val = t[1]**delta # Getting element * delta dummy
                    Np_Array[t[0]][diff-k] = Cal_val*counter # Fixing the final out in the postion mult by counter as power of column difference
                    counter =counter+1 # adding counter to next columns and row postion

    return Np_Array # Final result

Result_fun =  Vander_JD(List_A=List_A_define,N=N) # Passing value in Function
print (Result_fun)

[[   1    1    1    1    1    1]
 [  32   16    8    4    2    1]
 [ 243   81   27    9    3    1]
 [1024  256   64   16    4    1]]
